addSbtPlugin("com.eed3si9n"       % "sbt-assembly"                   % "1.2.0")
addSbtPlugin("io.spray"           % "sbt-revolver"                   % "0.9.1")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject"  % "1.2.0")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"               % "0.4.7")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"                   % "2.4.6")
